version: "3.8"

services:

  dns:
    build: ./dns
    command: -conf /root/Corefile
    ports:
      - "53:53/udp"
    volumes:
      - dns-config:/root/:rw
    networks:
      - outside

  node-api:
    build: ./web/backend
    volumes:
      - dns-config:/root/dns/:rw
    networks:
      - internal-net

  freeirc-com:
    build: ./web/frontend
    depends_on:
      - node-api
    ports:
      - "80:80"

    networks:
      - outside
      - internal-net

  freeirc-irc:
    init: true
    build: ergo-freeirc
    ports:
      - "10.0.2.16:6667:6667"
    networks:
      - outside


  probe-irc:
    init: true
    build: ergo-hosted
    ports:
      - "10.0.2.17:6667:6667/tcp"
    networks:
      - outside


volumes:
  dns-config:


networks:
  internal-net:
    driver: bridge
    internal: true

  outside:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: 'false'
